language: node_js

node_js:
  - "10"

branches:
  only:
    - dev

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn

script:
  - yarn testCoverage

after_success:
  - codecov
  - yarn build

env:
 global:
   - GH_REF: github.com/fanzhang15/11.git

after_script:
  - cd ./build
  - git init
  - git config user.name "${GITHUB_NAME}"
  - git config user.email "${GITHUB_EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOkEN}@${GH_REF}" master:master
